/*
Copyright 2012, 2013
Author Nicolas Edh,
Nicolas.Edh@gmail.com,
or user "nsf" at cfd-online.com

This file is part of hexBlocker.

    hexBlocker is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    hexBlocker is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with hexBlocker.  If not, see <http://www.gnu.org/licenses/>.

    The license is included in the file COPYING.
*/

#include "HexExporter.h"
#include "HexBlocker.h"
#include <iostream>
#include <QFile>
#include <QTextStream>

HexExporter::HexExporter()
{
}

HexExporter::HexExporter(HexBlocker *HB)
{
    hexB = HB;
    conv2meter=0.001;
}

void HexExporter::exporBlockMeshDict(QTextStream &out)
{
    out << "/*--------------------------------*- C++ -*----------------------------------*\\ "<<endl
        << "|             BlockMeshDict generated by hexBlocker                           | "<<endl
        << "\\*---------------------------------------------------------------------------*/ "<<endl
        << "FoamFile " << endl
        << "{" << endl
        << "\t version \t 2.0;" <<endl
        << "\t format \t ascii;" <<endl
        << "\t class \t\t dictionary; " <<endl
        << "\t object \t blockMeshDict; " << endl
        << "}" << endl;

    QString cnv2m;
    cnv2m.sprintf("%g",conv2meter);
    out << "convertToMeters " << cnv2m <<";" << endl;



    hexB->exportVertices(out);
    out << endl;
    hexB->exportBlocks(out);
    out << endl;
    hexB->exportBCs(out);
    out << endl;
    hexB->exportEdges(out);

}
